# Generated by Django 3.1.1 on 2020-12-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201222_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiontran',
            name='collectionheader',
        ),
        migrations.DeleteModel(
            name='CollectionHeader',
        ),
        migrations.DeleteModel(
            name='CollectionTran',
        ),
    ]
