# Generated by Django 3.1.1 on 2020-12-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201224_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.IntegerField(default=1),
        ),
    ]
