# Generated by Django 2.1.3 on 2021-01-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210101_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='designation',
            field=models.IntegerField(),
        ),
    ]
