# Generated by Django 2.1.3 on 2021-01-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210105_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='code',
            new_name='customercode',
        ),
        migrations.RenameField(
            model_name='employeedetail',
            old_name='code',
            new_name='employeecode',
        ),
        migrations.RenameField(
            model_name='entitydetail',
            old_name='code',
            new_name='entitycode',
        ),
    ]
